name: ðŸ¤– Build and deploy tagged version

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: "build-image"
  cancel-in-progress: false

jobs:
  build-image:
    name: Build Docker Image
    runs-on:
      - general
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          # use some obscure path to checkout the code with service account perms
          # this is possible as $GITHUB_WORKSPACE is owned by the same service
          # account
          # see: https://github.com/actions/checkout/issues/211
          path: __local

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: europe-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core
          tags: |
            type=ref,event=tag
            type=sha,prefix=,format=long

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: __local
          file: __local/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/cache:core
          cache-to: type=registry,ref=${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/cache:core,mode=max

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          echo "Signing images: $images"
          cosign sign --yes ${images}

  deploy-contract:
    name: Deploy contracts
    runs-on: general
    needs:
      - build-image
    container:
      image: ${{ vars.GCP_DOCKER_IMAGE_REGISTRY }}/core:${{ github.ref_name }}
      credentials:
        username: _json_key_base64
        password: ${{ secrets.GCP_DOCKER_IMAGES_REGISTRY_SERVICE_ACCOUNT }}

    steps:
      - name: Deploy contracts
        env:
          PRIVATE_KEY: "${{ secrets.TESTNET_DEPLOYER_PRIVATE_KEY }}"
          ETHERSCAN_API_KEY: "${{ secrets.TENDERLY_API_KEY }}"
          RPC_URL: "${{ vars.TENDERLY_MAINNET_RPC_URL }}"
          VERIFIER_URL: "${{ vars.TENDERLY_MAINNET_RPC_URL }}/verify/etherscan"
          MAX_OPEX_SPLIT: "5"
          MIN_METAPOOL_SPLIT: "0"
          CONTRACT_ADDRESSES: "/app/contract_addresses.txt"
          VERSION_TAG: "${{ github.ref_name }}"
        run: |
          cd /app
          mkdir -p ci
          touch .env
          yarn deploy:tenderly && (
            echo "VERSION_TAG=${VERSION_TAG}" >> $CONTRACT_ADDRESSES
            cp $CONTRACT_ADDRESSES $GITHUB_OUTPUT
            echo "# Smart contract addresses\n\n| Contract name | Address |\n|---|---|" > $GITHUB_STEP_SUMMARY
            grep ADDRESS $CONTRACT_ADDRESSES | awk -F '=' '{gsub("_ADDRESS", "", $1); print "| `" $1 "` | `" $2 "` |"}' >> $GITHUB_STEP_SUMMARY
            echo "\n# Other variables\n\n| Variable | Value |\n|---|---|" >> $GITHUB_STEP_SUMMARY
            grep -v ADDRESS $CONTRACT_ADDRESSES | awk -F '=' '{print "| `" $1 "` | `" $2 "` |"}' >> $GITHUB_STEP_SUMMARY
          )

      - name: Upload contract addresses artifact
        uses: actions/upload-artifact@v4
        with:
          name: contract_addresses
          path: /app/contract_addresses.txt
